Fixed some lexer-mll errors i got at compile time.
The errors and their fix
ERROR 1:
File "lexer.mll", line 74, characters 29-48:
Error: This expression has type int64 but an expression was expected of type
         int32
CAUSE:
Discreptency between AST using 32 and lexer using 64
Fix:
use
Int32.of_string s
instead of
Int64.of_string s
ERROR 2:
File "lexer.mll", line 79, characters 19-28:
Error: This variant expression is expected to have type Parser.token list
       There is no constructor INPUTLEFT within type list
CAUSE:
Almost all lexer rule returns a  a Parser.token list, but the InputLeft rule returns a single token (INPUTLEFT)
Fix:
Added the keywords to the id_or_kwd wich from what i gathered means identifier to keyword